spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
        consumer-in-0:
          destination: "test"
          group: "${spring.application.name}"
    function:
      definition: "consumer"